import { IndicatorData } from './types';

export const KEY_FIGURES = {
  sessions: 482,
  trainersInternal: 14,
  trainersExternal: 9,
  learners: 3254,
  revenue: "1.25M€",
  period: "Période 2025"
};

export const INDICATORS: IndicatorData[] = [
  {
    id: 1,
    criterionId: 1,
    criterionName: "Les conditions d’information du public sur les prestations proposées, les délais pour y accéder et les résultats obtenus",
    name: "Le prestataire diffuse une information accessible au public, détaillée et vérifiable sur les prestations proposées.",
    type: "Commun",
    specifics: { of: true, bc: true, vae: true, cfa: true },
    expectedLevel: "Donner une information accessible, exhaustive sur la prestation, c'est-à-dire sur son contenu et sur l'intégralité des items mentionnés. Cette information doit être à jour.",
    argalisHelp: "Vous définissez vos prestations, Argalis les met en forme. Depuis la fiche produit, vous générez automatiquement une fiche programme PDF complète et conforme. Toute mise à jour dans Argalis se répercute instantanément.",
    proofExamples: "Tous supports et outils d’information : plaquette, réseaux sociaux, sites internet, supports de publicité, salons, supports de contractualisation, CGV.",
    specificObligations: "VAE : les contraintes et exigences sont clairement formalisées. Formations certifiantes : mentionner le libellé exact, code RNCP/RS, certificateur et date.",
    subcontracting: "Non applicable si l'organisme intervient en sous-traitance (l'information revient au donneur d'ordres).",
    nonCompliance: "Mineure si information partiellement accessible ou absence ponctuelle de certains items.",
    auditObservation: "Les formations proposées sont disponibles sur le site internet de l’organisme : https://www.formajade.fr/?trk=public_post_reshare-text\n\nL’accessibilité au public en situation de handicap est communiquée sur le site internet via le logo « Handicap Repères validé » ainsi que les coordonnées du référent handicap pour toute question.\n\nLes programmes de formation sont transmis sur demande, ceux-ci mentionnent les prérequis, objectifs, durée, modalités et délais d’accès, tarifs, contacts, modalités d’évaluation, les moyens pédagogiques et techniques, l’accessibilité aux personnes handicapées.\n\nVu proposition commerciale et programme de formation correspondant pour la session Sauveteur Secouriste du Travail des 2 octobre et 9 octobre 2024."
  },
  {
    id: 2,
    criterionId: 1,
    criterionName: "Les conditions d’information du public sur les prestations proposées, les délais pour y accéder et les résultats obtenus",
    name: "Le prestataire diffuse des indicateurs de résultats adaptés à la nature des prestations mises en œuvre et des publics accueillis.",
    type: "Commun",
    specifics: { of: true, bc: true, vae: true, cfa: true },
    expectedLevel: "Donner une information chiffrée permettant de suivre les résultats de la prestation au regard des objectifs.",
    argalisHelp: "Vous réalisez les prestations, Argalis mesure leur succès. Via l'espace dématérialisé, vous collectez automatiquement les données clés : satisfaction, réussite, abandons. Argalis consolide ces résultats en rapports prêts à diffuser.",
    proofExamples: "Rapports d’activités, bilans, résultats d’enquêtes. Indicateurs : taux de satisfaction, nombre de stagiaires, abandons, réussite, insertion.",
    specificObligations: "CFA : indicateurs obligatoires (art. L. 6111-8). Diffusion via Inserjeunes ou calcul interne si indisponible.",
    subcontracting: "Non applicable en sous-traitance.",
    nonCompliance: "Mineure si information insuffisamment détaillée.",
    auditObservation: "Les indicateurs sont disponibles sur le site internet https://www.formajade.fr/pdf/1-5.pdf. Ils sont présentés par thématique de formation pour l’année 2024 et mis à jour tous les semestres.\n\nDonnées pour les thématiques Secourisme, Sécurité incendie, Habilitation électrique, Gestes et Postures, Engins de conduite :\n- Taux de satisfaction (entre 4,6 et 5/5)\n- Taux de rupture de parcours (0%)\n- Taux d’obtention de la certification (100%)\n- Taux de retour des enquêtes (100%)"
  },
  {
    id: 3,
    criterionId: 1,
    criterionName: "Les conditions d’information du public sur les prestations proposées, les délais pour y accéder et les résultats obtenus",
    name: "Le prestataire informe sur les taux d’obtention des certifications, blocs de compétences, équivalences et débouchés.",
    type: "Spécifique",
    specifics: { of: true, bc: false, vae: true, cfa: true },
    expectedLevel: "Donner au public une information accessible, exhaustive et actualisée sur les certifications.",
    argalisHelp: "Vous renseignez les taux d'obtention et débouchés dans Argalis. Nous intégrons automatiquement ces informations cruciales dans votre fiche programme pour une diffusion exhaustive.",
    proofExamples: "Supports d’information mentionnant les taux d’obtention, trajectoires d’évolution, taux d'insertion global et dans le métier visé.",
    specificObligations: "Nouveaux entrants : audité lors de la surveillance.",
    subcontracting: "Non applicable en sous-traitance.",
    nonCompliance: "Mineure si information partielle ou absence ponctuelle.",
    auditObservation: "Non applicable / Sans objet. Pas de formation certifiante en propre (erreur BPF signalée)."
  },
  {
    id: 4,
    criterionId: 2,
    criterionName: "L’identification précise des objectifs des prestations proposées et l’adaptation de ces prestations aux publics bénéficiaires",
    name: "Le prestataire analyse le besoin du bénéficiaire en lien avec l’entreprise et/ou le financeur concerné(s).",
    type: "Commun",
    specifics: { of: true, bc: true, vae: true, cfa: true },
    expectedLevel: "Démontrer comment le besoin du bénéficiaire est analysé en fonction de la finalité de la prestation.",
    argalisHelp: "Argalis structure votre analyse dans une fiche dédiée (attentes, solutions pédagogiques, handicap) automatiquement annexée à la proposition commerciale.",
    proofExamples: "Grilles d’analyse, diagnostics préalables, dossiers d’admission, comptes rendus d’entretiens.",
    specificObligations: "PSH : démontrer la prise en compte des besoins en compensation. CFA/Alternance : analyse en amont de la contractualisation.",
    subcontracting: "Le sous-traitant doit démontrer qu'il tient compte de l'analyse du besoin.",
    nonCompliance: "Majeure.",
    auditObservation: "Analyse des attentes, contraintes règlementaires et situations de handicap formalisée dans la fiche d’analyse de besoins renseignée en amont de la formation lors d'un rendez-vous personnalisé.\n\nVu Registre de Management de la Qualité avec Procédure d’identification des besoins.\nVu logiciel ARGALIS qui trace tous les échanges avec le client.\nVu demande pour client André Renault (incendie, secourisme, CSE) et FC Nantes (Equipier 1ere intervention)."
  },
  {
    id: 5,
    criterionId: 2,
    criterionName: "L’identification précise des objectifs des prestations proposées et l’adaptation de ces prestations aux publics bénéficiaires",
    name: "Le prestataire définit les objectifs opérationnels et évaluables de la prestation.",
    type: "Commun",
    specifics: { of: true, bc: true, vae: true, cfa: true },
    expectedLevel: "Démontrer que les objectifs spécifiques ont été définis et peuvent faire l’objet d’une évaluation.",
    argalisHelp: "Vous définissez les objectifs dans la fiche produit. Argalis les intègre aux conventions et à l'interface intervenant pour évaluation directe.",
    proofExamples: "Programmes, supports de contractualisation, compétences visées, référentiels.",
    specificObligations: "CFA : objectifs exprimés en compétences. Certifiant : conformité au RNCP/RS.",
    subcontracting: "Prendre en compte les objectifs définis par le donneur d'ordres.",
    nonCompliance: "Majeure.",
    auditObservation: "Vu objectifs présentés dans le programme de formation « Equipier de 1ere intervention » :\n- Être capable d’identifier les notions éléments de propagation de l’incendie\n- Utiliser efficacement l’ensemble des moyens dédiés (plan d’évacuation, extincteur, réalité augmentée)\n\nLe programme de formation présente les objectifs, ceux-ci sont bien formulés de façon opérationnelles et évaluables."
  },
  {
    id: 6,
    criterionId: 2,
    criterionName: "L’identification précise des objectifs des prestations proposées et l’adaptation de ces prestations aux publics bénéficiaires",
    name: "Le prestataire établit les contenus et les modalités de mise en œuvre adaptés aux objectifs et aux publics.",
    type: "Commun",
    specifics: { of: true, bc: true, vae: true, cfa: true },
    expectedLevel: "Contenus et modalités adaptés aux objectifs définis en fonction des bénéficiaires.",
    argalisHelp: "Déposez des déroulés pédagogiques distincts par modalité (Présentiel, E-learning) dans Argalis. L'intervenant n'accède qu'au déroulé pertinent.",
    proofExamples: "Déroulés, séquences, grilles, modalités d’accompagnement, calendrier.",
    specificObligations: "Certifiant : cohérence avec le référentiel. PSH : prise en compte dans la conception.",
    subcontracting: "",
    nonCompliance: "Majeure.",
    auditObservation: "Un synopsis est systématiquement établi pour chaque formation reprenant les objectifs, contenu et méthodes / moyens pédagogiques.\nLe contenu de la formation est construit à partir des documents mis à disposition sur le site de l’INRS.\nVu programme et synopsis pour la formation « Equipier de 1ere intervention »."
  },
  {
    id: 7,
    criterionId: 2,
    criterionName: "L’identification précise des objectifs des prestations proposées et l’adaptation de ces prestations aux publics bénéficiaires",
    name: "Adéquation des contenus aux exigences de la certification visée (formations certifiantes).",
    type: "Spécifique",
    specifics: { of: true, bc: false, vae: false, cfa: true },
    expectedLevel: "Démontrer l’adéquation du contenu aux compétences ciblées et aux épreuves d’évaluation.",
    argalisHelp: "Joignez votre tableau de correspondance (mapping) à la fiche produit dans Argalis pour prouver l'adéquation.",
    proofExamples: "Tableau croisé contenu/référentiel, habilitation du prestataire, convention avec le certificateur.",
    specificObligations: "",
    subcontracting: "L'organisme certificateur tient compte des missions confiées.",
    nonCompliance: "Majeure.",
    auditObservation: "Sans objet (pas de formation certifiante)."
  },
  {
    id: 8,
    criterionId: 2,
    criterionName: "L’identification précise des objectifs des prestations proposées et l’adaptation de ces prestations aux publics bénéficiaires",
    name: "Le prestataire détermine les procédures de positionnement et d’évaluation des acquis à l’entrée.",
    type: "Spécifique",
    specifics: { of: true, bc: false, vae: false, cfa: true },
    expectedLevel: "Démontrer la mise en œuvre des procédures de positionnement adaptées.",
    argalisHelp: "Diffusez des quiz et modules d'auto-positionnement via l'espace dématérialisé Argalis avant l'entrée en formation.",
    proofExamples: "Diagnostic préalable, quiz, QCM, exercices, entretien, audit, tests.",
    specificObligations: "Certifiant : prérequis cohérents avec la certification.",
    subcontracting: "",
    nonCompliance: "Mineure si dispositif existant mais incomplet.",
    auditObservation: "Vu programme de formation Recyclage SST qui mentionne le prérequis suivant : Avoir le certificat de formation initial SST. Ces éléments sont vérifiés en amont.\n\nToutes les formations ont une autoévaluation en début de formation, via un QR code transmis dans les convocations."
  },
  {
    id: 9,
    criterionId: 3,
    criterionName: "L’adaptation aux publics bénéficiaires des prestations et des modalités d’accueil, d’accompagnement, de suivi et d’évaluation",
    name: "Le prestataire informe les publics bénéficiaires des conditions de déroulement de la prestation.",
    type: "Commun",
    specifics: { of: true, bc: true, vae: true, cfa: true },
    expectedLevel: "Les modalités d’accueil et conditions de déroulement sont formalisées et diffusées.",
    argalisHelp: "Centralisez règlement intérieur, livret d'accueil et CGU dans Argalis pour un accès permanent via l'espace stagiaire.",
    proofExamples: "Règlement intérieur, livret d’accueil, convocation, référents, modalités FOAD.",
    specificObligations: "CBC : engagements déontologiques.",
    subcontracting: "",
    nonCompliance: "Mineure si information incomplète.",
    auditObservation: "Vu convocation mentionnant éléments pratiques et QR code. Le QR Code permet l’émargement et l’accès au questionnaire d’évaluation, règlement intérieur, convention de formation, programme.\nCes éléments ont pu être consultés pour le dossier de formation « Equipier de 1ere intervention »."
  },
  {
    id: 10,
    criterionId: 3,
    criterionName: "L’adaptation aux publics bénéficiaires des prestations et des modalités d’accueil, d’accompagnement, de suivi et d’évaluation",
    name: "Le prestataire met en œuvre et adapte la prestation, l’accompagnement et le suivi aux bénéficiaires.",
    type: "Commun",
    specifics: { of: true, bc: true, vae: true, cfa: true },
    expectedLevel: "Adaptation aux situations et profils (contenus, rythmes, accompagnement).",
    argalisHelp: "Les intervenants déposent leurs comptes-rendus d'adaptation directement dans l'espace session d'Argalis.",
    proofExamples: "Emplois du temps adaptés, groupes de niveaux, livreets de suivi, adaptations PSH.",
    specificObligations: "CFA : accompagnement des apprentis. VAE : adaptation durée/modalités.",
    subcontracting: "",
    nonCompliance: "Majeure.",
    auditObservation: "Le contenu est défini dans le synopsis de la formation, celui-ci est conforme aux documents transmis par l’INRS.\nLe synopsis définit également les outils et l’accompagnement prévu des apprenants."
  },
  {
    id: 11,
    criterionId: 3,
    criterionName: "L’adaptation aux publics bénéficiaires des prestations et des modalités d’accueil, d’accompagnement, de suivi et d’évaluation",
    name: "Le prestataire évalue l’atteinte par les publics bénéficiaires des objectifs de la prestation.",
    type: "Commun",
    specifics: { of: true, bc: true, vae: true, cfa: true },
    expectedLevel: "Un processus d’évaluation formalisé permet d’apprécier l’atteinte des objectifs.",
    argalisHelp: "Déployez des quiz et générez des attestations de fin de formation avec niveaux d'acquisition directement depuis Argalis.",
    proofExamples: "QCM, entretiens, mises en situation, taux de réussite, livrets de compétences.",
    specificObligations: "VAE : dossier de suivi.",
    subcontracting: "",
    nonCompliance: "Majeure.",
    auditObservation: "Toutes les formations font l’objet d’une évaluation en fin de formation renseignée via le QR code transmis sur la convocation.\nLes éléments consultés permettent de mesurer l’atteinte des objectifs définis en amont de la formation, via un même questionnaire d’autoévaluation transmis en début et en fin de formation, complété par une évaluation du formateur."
  },
  {
    id: 12,
    criterionId: 3,
    criterionName: "L’adaptation aux publics bénéficiaires des prestations et des modalités d’accueil, d’accompagnement, de suivi et d’évaluation",
    name: "Le prestataire favorise l’engagement des bénéficiaires et prévient les ruptures de parcours.",
    type: "Commun",
    specifics: { of: true, bc: true, vae: true, cfa: true },
    expectedLevel: "Mesures formalisées pour formations > 2 jours.",
    argalisHelp: "Signalez absences et risques de rupture dans le module Qualité. Tracez les relances et plans d'action.",
    proofExamples: "Relances, carnet de RDV, interactivité pédagogique, prévention des abandons.",
    specificObligations: "CFA : accompagnement des apprentis, aide à la recherche d'entreprise.",
    subcontracting: "",
    nonCompliance: "Mineure.",
    auditObservation: "Applicable aux formations > 2 jours (ex: Habilitation électrique de 3 jours).\nAucun abandon enregistré.\nEn cas d’absence d’une journée d’un stagiaire, la journée est replanifiée sur une autre session.\nVu PRG3 Procédure de réalisation avec § prévention et de gestion des ruptures."
  },
  {
    id: 13,
    criterionId: 3,
    criterionName: "L’adaptation aux publics bénéficiaires des prestations et des modalités d’accueil, d’accompagnement, de suivi et d’évaluation",
    name: "Coordination et progressivité des apprentissages en centre et en entreprise (Alternance).",
    type: "Spécifique",
    specifics: { of: true, bc: false, vae: false, cfa: true },
    expectedLevel: "Processus formalisé d’articulation itératif des apprentissages.",
    argalisHelp: "Partagez les comptes-rendus de visite et livrets de suivi avec les tuteurs via l'espace documentaire partagé.",
    proofExamples: "Carnet de liaison, visites d'entreprise, plannings partagés.",
    specificObligations: "",
    subcontracting: "",
    nonCompliance: "Mineure.",
    auditObservation: "Sans Objet (Pas de formation en alternance)."
  },
  {
    id: 14,
    criterionId: 3,
    criterionName: "L’adaptation aux publics bénéficiaires des prestations et des modalités d’accueil, d’accompagnement, de suivi et d’évaluation",
    name: "Accompagnement socio-professionnel, éducatif et relatif à l’exercice de la citoyenneté.",
    type: "Spécifique",
    specifics: { of: false, bc: false, vae: false, cfa: true },
    expectedLevel: "L’accompagnement est formalisé et mis en œuvre par des projets spécifiques.",
    argalisHelp: "Centralisez chartes, projets et listes de partenaires sociaux dans l'espace organisme.",
    proofExamples: "Projets sportifs/culturels, aides financières, listes intervenants sociaux, mixité.",
    specificObligations: "",
    subcontracting: "",
    nonCompliance: "Majeure.",
    auditObservation: "Sans Objet (Pas de CFA)."
  },
  {
    id: 15,
    criterionId: 3,
    criterionName: "L’adaptation aux publics bénéficiaires des prestations et des modalités d’accueil, d’accompagnement, de suivi et d’évaluation",
    name: "Information des apprentis sur leurs droits, devoirs, santé et sécurité.",
    type: "Spécifique",
    specifics: { of: false, bc: false, vae: false, cfa: true },
    expectedLevel: "Démontrer que les apprentis sont informés.",
    argalisHelp: "Argalis rend le règlement intérieur et les fiches sécurité accessibles en permanence dans l'espace de l'apprenti.",
    proofExamples: "Règlement intérieur, supports d'info, CR réunions de rentrée.",
    specificObligations: "",
    subcontracting: "",
    nonCompliance: "Majeure.",
    auditObservation: "Sans Objet (Pas de CFA)."
  },
  {
    id: 16,
    criterionId: 3,
    criterionName: "L’adaptation aux publics bénéficiaires des prestations et des modalités d’accueil, d’accompagnement, de suivi et d’évaluation",
    name: "Respect des exigences formelles de l’autorité de certification pour la présentation aux examens.",
    type: "Spécifique",
    specifics: { of: true, bc: false, vae: true, cfa: true },
    expectedLevel: "Respect des conditions de présentation des candidats.",
    argalisHelp: "Associez référentiels et règlements d'examen aux produits dans Argalis pour une communication claire.",
    proofExamples: "Information candidats, inscriptions, habilitations, PV d'examen.",
    specificObligations: "",
    subcontracting: "",
    nonCompliance: "Majeure.",
    auditObservation: "Sans Objet (Pas de formation certifiante en propre)."
  },
  {
    id: 17,
    criterionId: 4,
    criterionName: "L’adéquation des moyens pédagogiques, techniques et d’encadrement aux prestations mises en oeuvre",
    name: "Mise à disposition de moyens humains et techniques adaptés et d’un environnement approprié.",
    type: "Commun",
    specifics: { of: true, bc: true, vae: true, cfa: true },
    expectedLevel: "Locaux, équipements et moyens humains en adéquation avec la prestation.",
    argalisHelp: "Gestion des compétences : n'affectez que des intervenants conformes. Rattachez les moyens logistiques aux prestations.",
    proofExamples: "Bail, registre accessibilité, matériel, LMS, CV intervenants.",
    specificObligations: "CBC : confidentialité.",
    subcontracting: "",
    nonCompliance: "Mineure.",
    auditObservation: "Moyens humains : Vu Organigramme à jour et liste des formateurs sous Argalis.\nMoyens techniques : Les formations ont lieu dans les locaux du client et exceptionnellement dans les locaux de l’organisme ou au casino de St Brevin.\nVu convention de formation « Equipier de 1ere intervention » mentionnant les moyens nécessaires.\nDocument unique, Registre de sécurité, Registre du personnel disponibles.\nDouble sauvegarde des données réalisée."
  },
  {
    id: 18,
    criterionId: 4,
    criterionName: "L’adéquation des moyens pédagogiques, techniques et d’encadrement aux prestations mises en oeuvre",
    name: "Le prestataire mobilise et coordonne les différents intervenants internes et/ou externes.",
    type: "Commun",
    specifics: { of: true, bc: true, vae: true, cfa: true },
    expectedLevel: "Identification et coordination des fonctions nécessaires.",
    argalisHelp: "Fiches intervenants détaillées dans Argalis. Affectation claire aux sessions pour coordonner les rôles.",
    proofExamples: "Organigramme, contrats, fiches de poste, plannings, comptes-rendus réunions.",
    specificObligations: "",
    subcontracting: "",
    nonCompliance: "Mineure.",
    auditObservation: "Identification : Vu Organigramme et liste des formateurs sous Argalis.\nMissions : Les thématiques de formation sont renseignées sous Argalis pour chacun des formateurs. L’affectation n'est possible que si le formateur est habilité.\nCoordination : Vu planning de formation sous Argalis. Vu contrat de sous-traitance (Ludovic Papin) mentionnant la mission confiée."
  },
  {
    id: 19,
    criterionId: 4,
    criterionName: "L’adéquation des moyens pédagogiques, techniques et d’encadrement aux prestations mises en oeuvre",
    name: "Mise à disposition de ressources pédagogiques et appropriation par le bénéficiaire.",
    type: "Commun",
    specifics: { of: true, bc: true, vae: true, cfa: true },
    expectedLevel: "Ressources existantes, actualisées, disponibles et facilitant l'appropriation.",
    argalisHelp: "Portail ressources apprenant structuré par module dans Argalis, accessible tout au long du parcours.",
    proofExamples: "Supports de cours, vidéos, bibliothèques, accès LMS, tutoriels.",
    specificObligations: "FOAD : assistance technique et pédagogique.",
    subcontracting: "",
    nonCompliance: "Mineure.",
    auditObservation: "Documents systématiquement remis en fin de formation : attestation de présence, support stagiaire, flyer technique et ressources complémentaires.\nVu supports remis aux stagiaires pour la formation « Equipier de 1ere intervention »."
  },
  {
    id: 20,
    criterionId: 4,
    criterionName: "L’adéquation des moyens pédagogiques, techniques et d’encadrement aux prestations mises en oeuvre",
    name: "Personnel dédié : mobilité, référent handicap, conseil de perfectionnement.",
    type: "Spécifique",
    specifics: { of: false, bc: false, vae: false, cfa: true },
    expectedLevel: "Présenter listes, contacts et PV pour ces fonctions.",
    argalisHelp: "Archivez les nominations et PV de conseil de perfectionnement dans l'espace documentaire Argalis.",
    proofExamples: "Membres conseil perfectionnement, référent mobilité, référent handicap, PV nomination.",
    specificObligations: "",
    subcontracting: "",
    nonCompliance: "Majeure.",
    auditObservation: "Sans Objet (Pas de CFA)."
  },
  {
    id: 21,
    criterionId: 5,
    criterionName: "La qualification et le développement des connaissances et compétences des personnels chargés de mettre en œuvre les prestations",
    name: "Le prestataire détermine, mobilise et évalue les compétences des intervenants.",
    type: "Commun",
    specifics: { of: true, bc: true, vae: true, cfa: true },
    expectedLevel: "Compétences définies en amont, adaptées et évaluées.",
    argalisHelp: "Définissez les exigences (diplômes, certificats) par formation. Argalis bloque l'affectation si non-conforme.",
    proofExamples: "CV, diplômes, plan de développement des compétences, entretiens annuels.",
    specificObligations: "VAE : formation à l'analyse des référentiels.",
    subcontracting: "",
    nonCompliance: "Majeure.",
    auditObservation: "Vu PRG4 Procédure RH qui décrit la sélection d’un nouveau formateur (prérequis, diplômes, entretien).\nVu éléments pour le recrutement d’Alexis Reboux en janvier 2024.\nMaitrise/mobilisation : validation des compétences enregistrées dans Argalis avant affectation.\nEvaluation : entretien professionnel tous les 2 ans, retours questionnaires stagiaires."
  },
  {
    id: 22,
    criterionId: 5,
    criterionName: "La qualification et le développement des connaissances et compétences des personnels chargés de mettre en œuvre les prestations",
    name: "Le prestataire entretient et développe les compétences de ses salariés.",
    type: "Commun",
    specifics: { of: true, bc: true, vae: true, cfa: true },
    expectedLevel: "Mobilisation des leviers de formation continue.",
    argalisHelp: "Centralisez CV et attestations de formation dans les fiches salariés Argalis. Archivez le plan de développement.",
    proofExamples: "Plan de formation, attestations, veille, groupes d'analyse de pratiques.",
    specificObligations: "",
    subcontracting: "",
    nonCompliance: "Majeure.",
    auditObservation: "Les besoins de formations sont identifiés lors des entretiens professionnels ou via les rappels Argalis.\nToutes les formations suivies sont enregistrées dans Argalis avec alerte pour validité.\nVu formation habilitation électrique pour David Robion.\nVu formation AGEPHIP « Référent handicap » suivi par Mr Robion le 12 octobre 2023."
  },
  {
    id: 23,
    criterionId: 6,
    criterionName: "L’inscription et l’investissement du prestataire dans son environnement professionnel",
    name: "Veille légale et réglementaire et exploitation des enseignements.",
    type: "Commun",
    specifics: { of: true, bc: true, vae: true, cfa: true },
    expectedLevel: "Démontrer la mise en place d’une veille et son exploitation.",
    argalisHelp: "Module Qualité pour tracer les veilles, sources et plans d'action associés.",
    proofExamples: "Abonnements, salons, actualisation supports, PV réunions.",
    specificObligations: "",
    subcontracting: "",
    nonCompliance: "Mineure.",
    auditObservation: "Mr Robion en charge de la veille.\nSources : OPCO, Centre Inffo, Gref de Bretagne.\nVu suivi de la veille I23 I24 I25.\nExemple exploitation : Décret du 23 mai 2023 (affichage Qualiopi) et V9 du Guide de lecture."
  },
  {
    id: 24,
    criterionId: 6,
    criterionName: "L’inscription et l’investissement du prestataire dans son environnement professionnel",
    name: "Veille compétences, métiers, emplois et exploitation.",
    type: "Commun",
    specifics: { of: true, bc: true, vae: true, cfa: true },
    expectedLevel: "Veille sur les métiers/compétences et impact sur les prestations.",
    argalisHelp: "Tracez l'analyse de l'évolution des métiers dans le module Qualité Argalis.",
    proofExamples: "Conférences, réseaux pro, études, mise à jour des contenus.",
    specificObligations: "",
    subcontracting: "",
    nonCompliance: "Mineure.",
    auditObservation: "Mr Robion et Mr Morvan en charge.\nSources : INRS, CARSAT, ANACT.\nExemple exploitation : Utilisation de la réalité augmentée pour les formations incendie, étude d'un escape game pour secourisme."
  },
  {
    id: 25,
    criterionId: 6,
    criterionName: "L’inscription et l’investissement du prestataire dans son environnement professionnel",
    name: "Veille innovations pédagogiques et technologiques et exploitation.",
    type: "Commun",
    specifics: { of: true, bc: true, vae: true, cfa: true },
    expectedLevel: "Veille innovation et impact sur les prestations.",
    argalisHelp: "Documentez vos tests d'outils et évolutions pédagogiques dans Argalis.",
    proofExamples: "Salons, webinaires, achat matériel innovant, nouveaux outils LMS.",
    specificObligations: "",
    subcontracting: "",
    nonCompliance: "Mineure.",
    auditObservation: "Veille sur innovations pédagogiques et technologiques.\nExemple : Veille INRS Janvier 2024 (modification référentiel SST), mise à jour vidéos SST au 01/07/24."
  },
  {
    id: 26,
    criterionId: 6,
    criterionName: "L’inscription et l’investissement du prestataire dans son environnement professionnel",
    name: "Mobilisation des expertises et réseaux pour l'accueil du public en situation de handicap.",
    type: "Commun",
    specifics: { of: true, bc: true, vae: true, cfa: true },
    expectedLevel: "Réseau de partenaires handicap mobilisable et mesures spécifiques.",
    argalisHelp: "Liste partenaires (Agefiph, Cap emploi) et preuves de contact centralisées dans l'espace organisme.",
    proofExamples: "Liste partenaires, charte accessibilité, compétences référent handicap.",
    specificObligations: "",
    subcontracting: "Le prestataire doit disposer du réseau ou utiliser celui du donneur d'ordre.",
    nonCompliance: "Majeure.",
    auditObservation: "Mr Robion identifié comme interlocuteur.\nVu registre Management de la Qualité avec adresses et contacts (Agefiph).\nVu attestation de formation AGEPHIP « Référent handicap » pour Mr Robion."
  },
  {
    id: 27,
    criterionId: 6,
    criterionName: "L’inscription et l’investissement du prestataire dans son environnement professionnel",
    name: "Respect de la conformité au référentiel par les sous-traitants et salariés portés.",
    type: "Commun",
    specifics: { of: true, bc: true, vae: true, cfa: true },
    expectedLevel: "Dispositions pour vérifier la conformité des sous-traitants.",
    argalisHelp: "Tracez la sélection, les chartes et contrats de sous-traitance dans Argalis.",
    proofExamples: "Contrats, process sélection, charte qualité signée, justificatifs.",
    specificObligations: "",
    subcontracting: "",
    nonCompliance: "Majeure.",
    auditObservation: "Vu registre Management de la Qualité avec PRG4 Procédure Ressources RH.\nVu contrat de sous-traitance Ludovic Papin (mission du 18 juillet). Certifié Qualiopi depuis février 2024 (attestation ICERT vue)."
  },
  {
    id: 28,
    criterionId: 6,
    criterionName: "L’inscription et l’investissement du prestataire dans son environnement professionnel",
    name: "Mobilisation du réseau de partenaires pour la formation en situation de travail (Alternance).",
    type: "Spécifique",
    specifics: { of: true, bc: false, vae: false, cfa: true },
    expectedLevel: "Existence d'un réseau mobilisé pour l'accueil en entreprise.",
    argalisHelp: "Centralisez conventions et contacts entreprises dans Argalis.",
    proofExamples: "Liste entreprises, conventions, comités pilotage, visites.",
    specificObligations: "",
    subcontracting: "",
    nonCompliance: "Mineure.",
    auditObservation: "Sans Objet (Pas d'alternance)."
  },
  {
    id: 29,
    criterionId: 6,
    criterionName: "L’inscription et l’investissement du prestataire dans son environnement professionnel",
    name: "Actions concourant à l’insertion professionnelle ou la poursuite d’étude.",
    type: "Spécifique",
    specifics: { of: false, bc: false, vae: false, cfa: true },
    expectedLevel: "Développer des actions pour l'insertion.",
    argalisHelp: "Documentez forums, ateliers CV et partenariats insertion dans Argalis.",
    proofExamples: "Salons, visites, ateliers recherche emploi, réseau anciens.",
    specificObligations: "",
    subcontracting: "",
    nonCompliance: "Majeure.",
    auditObservation: "Sans Objet (Pas de CFA)."
  },
  {
    id: 30,
    criterionId: 7,
    criterionName: "Le recueil et la prise en compte des appréciations et des réclamations formulées par les parties prenantes aux prestations délivrées",
    name: "Recueil des appréciations : bénéficiaires, financeurs, équipe pédagogique, entreprises.",
    type: "Commun",
    specifics: { of: true, bc: true, vae: true, cfa: true },
    expectedLevel: "Sollicitation à fréquence pertinente, relances, libre expression.",
    argalisHelp: "Questionnaires à chaud/froid intégrés. Consolidation auto des réponses bénéficiaires/formateurs.",
    proofExamples: "Enquêtes satisfaction, CR entretiens, analyse appréciations, réunions financeurs.",
    specificObligations: "CBC : Bénéficiaires et équipes seulement.",
    subcontracting: "",
    nonCompliance: "Mineure.",
    auditObservation: "Recueil en place pour toutes les parties.\nBénéficiaires : questionnaire en fin de formation (QR Code).\nEquipes pédagogiques : questionnaire fin de formation et entretiens.\nEntreprises/Financeurs : sollicitation via questionnaire transmis avec la facture.\nRelance prévue."
  },
  {
    id: 31,
    criterionId: 7,
    criterionName: "Le recueil et la prise en compte des appréciations et des réclamations formulées par les parties prenantes aux prestations délivrées",
    name: "Traitement des difficultés, réclamations et aléas.",
    type: "Commun",
    specifics: { of: true, bc: true, vae: true, cfa: true },
    expectedLevel: "Modalités de traitement définies et mises en œuvre.",
    argalisHelp: "Enregistrez et documentez chaque aléa/réclamation dans le module Qualité.",
    proofExamples: "Registre réclamations, accusés réception, réponses, solutions apportées.",
    specificObligations: "",
    subcontracting: "",
    nonCompliance: "Majeure.",
    auditObservation: "Enregistrement systématique dans Argalis. 3 enregistrements depuis sept 2023 (ex: rupture livret, refus formateur par client, bouteille gaz vide).\nVu compte rendu réunion qualité du 19/08/24 analysant ces dysfonctionnements."
  },
  {
    id: 32,
    criterionId: 7,
    criterionName: "Le recueil et la prise en compte des appréciations et des réclamations formulées par les parties prenantes aux prestations délivrées",
    name: "Mesures d’amélioration à partir de l’analyse des appréciations et réclamations.",
    type: "Commun",
    specifics: { of: true, bc: true, vae: true, cfa: true },
    expectedLevel: "Démarche d’amélioration continue.",
    argalisHelp: "Liez réclamations et plans d'action dans Argalis pour prouver l'amélioration continue.",
    proofExamples: "Plans d'action, suivi mesures correctives, analyse causes abandons.",
    specificObligations: "",
    subcontracting: "",
    nonCompliance: "Majeure.",
    auditObservation: "Réunions qualité régulières (Direction + Ref Pédagogique). Ordre du jour : indicateurs, retours, veille.\nPoint Fort identifié : mise en place de la réalité augmentée et utilisation de l'IA pour quizzs."
  }
];